# Generated by Django 3.0.6 on 2020-05-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
