# Generated by Django 3.0.6 on 2020-05-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_web', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
